version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      # - deploy:
      #     name: Trigger docs deployment
      #     working_directory: ~/workdir/docs
      #     command: |
      #       git config credential.helper 'cache --timeout=120'
      #       git config user.email "olagunjuadewale5@gmail.com"
      #       git config user.name "dewale005"
      #       git commit --allow-empty -m "Trigger deployment from circle ci"
      #       git push origin master

workflows:
    build-and-test:
      jobs:
        - build-and-test